AVERAGE_LABEL_BUILDING_BLOCK = "average_"
NORMALIZED_LABEL_BUILDING_BLOCK = "normalized_"

GOAL_LABEL = "goal"
ASSIST_LABEL = "assist"
MINUTES_PLAYED = "minutes_played"

RED_CARD_LABEL = "red_card"
YELLOW_CARD_LABEL = "yellow_card"

RATING_LABEL = "rating"

PLAYER_ID_LABEL = "player_id"
GAME_COUNT_LABEL = "game_count"


NORMALIZED_GOAL_LABEL = NORMALIZED_LABEL_BUILDING_BLOCK + GOAL_LABEL
NORMALIZED_ASSIST_LABEL = NORMALIZED_LABEL_BUILDING_BLOCK + ASSIST_LABEL
NORMALIZED_MINUTES_PLAYED = NORMALIZED_LABEL_BUILDING_BLOCK + MINUTES_PLAYED

NORMALIZED_RED_CARD = NORMALIZED_LABEL_BUILDING_BLOCK + RED_CARD_LABEL
NORMALIZED_YELLOW_CARD = NORMALIZED_LABEL_BUILDING_BLOCK + YELLOW_CARD_LABEL

NORMALIZED_RATING_LABEL = NORMALIZED_LABEL_BUILDING_BLOCK + RATING_LABEL

RELEVANT_QUERY_LABELS = [YELLOW_CARD_LABEL, RED_CARD_LABEL, GOAL_LABEL, ASSIST_LABEL, MINUTES_PLAYED]
